# Generated by Django 4.2.9 on 2024-03-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0007_reportfile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReportFile",
        ),
    ]
