# Generated by Django 4.2.9 on 2024-03-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_notification_periodicallynotification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="is_notified",
            field=models.BooleanField(default=False),
        ),
    ]
